database:
  host: 182.254.243.143
  port: 3306
  dbname: app_db
  user: test
  password: D7p6ZkcJRMynPfCy

redis:
  host: 182.254.243.143
  port: 6379
  password: "32wB6ejWwb78cPKT"
  db: 0

jwt:
  secret: your-secret
  expire_time: 86400  # token 过期时间，单位：秒，默认 24 小时

server:
  port: 8080
  mode: debug  # debug, release, test